[theme]
primaryColor = '#005358'  
backgroundColor = '#FFFFFF'
secondaryBackgroundColor = '#f2f2f2'
textColor = '#302E30'
font = "sans serif"

[server]
# Unclear whether needed, Default: 200 Mb
maxUploadSize = 500
# TODO: Configure server e.g., ServerAliveInterval=60

[browser]
# To share app addresses on MarIuX-networked computers, must set IP address to e.g., bohemianrhapsody
serverAddress = bohemianrhapsody.molgen.mpg.de
